name: Build for x64 ubuntu-latest

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build for x64 ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up environment
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libusb-1.0-0-dev libbz2-dev libzstd-dev asciidoc rename

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: uuu
          path: ./build/uuu/uuu

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          name: Release UUU_1.5.${{ github.sha }}_TEST
          tag: UUU_1.5.${{ github.sha }}_TEST
          commit: ${{ github.hash }}
          allowUpdates: true
          draft: true
          prerelease: true
          artifacts: "./build/uuu/uuu"
