name: Build for x64 ubuntu-lastest

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for x64 ubuntu-lastest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up environment
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libusb-1.0-0-dev libbz2-dev libzstd-dev asciidoc rename

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

