name: Build for x64 ubuntu

on:
  push:
    branches:
      - master
    tags:
      - uuu*
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build for x64 ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libusb-1.0-0-dev libbz2-dev libzstd-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload Build Artifacts
        if: ${{ matrix.os }} == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          name: uuu
          path: ./build/uuu/uuu

      - name: Create or Update Release
        if: ${{ matrix.os }} == 'ubuntu-20.04'
        uses: ncipollo/release-action@v1
        with:
          name: Release UUU_1.5.${{ github.sha }}_TEST
          tag: UUU_1.5.${{ github.sha }}_TEST
          commit: ${{ github.hash }}
          allowUpdates: true
          draft: true
          prerelease: true
          artifacts: "./build/uuu/uuu"
