name: Build for x64 ubuntu-latest

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build for x64 ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up environment
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libusb-1.0-0-dev libbz2-dev libzstd-dev asciidoc rename

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Create or Update Release
        id: create_or_update_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: UUU_1.5.${{ github.run_id }}_TEST
          release_name: Release UUU_1.5.${{ github.sha }}_TEST
          draft: true
          prerelease: true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: uuu
          path: ./build/uuu/uuu
