name: Build pdf document

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build for pdf
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: nxp-imx/mfgtools.wiki.git
          path: wiki
          ref: master

      - name: Set up environment
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install asciidoc rename

      - name: Build
        run: |
          cd wiki
          rename -f 's/\.asciidoc$//' *
          echo "<revhistory>" > UUU-docinfo.xml
          git log -n25 --reverse --format="format:<revision><revnumber>%h</revnumber><date>%cd</date><authorinitials>%an</authorinitials><revremark>%s</revremark></revision>" >> UUU-docinfo.xml
          echo "</revhistory>" >> UUU-docinfo.xml
          a2x -L -a docinfo UUU

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: UUU.pdf
          path: wiki/UUU.pdf

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          name: Release UUU_1.5.${{ github.sha }}_TEST
          tag: UUU_1.5.${{ github.sha }}_TEST
          commit: ${{ github.hash }}
          allowUpdates: true
          draft: true
          prerelease: true
          artifacts: "wiki/UUU.pdf"
