name: macOS Build

on:
  push:
    branches:
      - master
    tags:
      - uuu*
  pull_request:
    types:
      - opened
      - synchronize
      
jobs:
  build:
    name: macOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment
        run: brew install libusb pkg-config zstd
        
      - name: Build
        run: export PATH="/usr/local/Cellar/pkg-config/0.29.2_3/bin:${PATH}"; pkg-config --list-all; cmake -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl . ; make

      - name: Rename
        run: cp uuu/uuu uuu_mac
    
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: uuu_mac
          path: uuu/uuu

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          allowUpdates: true
          draft: true
          prerelease: true
          artifacts: "uuu_mac"
