name: Build with VS Studio

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: ['Debug', 'Release']
        platform: ['x86', 'x64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1
  
    - name: Restore NuGet packages
      run: nuget restore YourSolution.sln
    
    - name: Build static solution
      run: msbuild /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} msvc/uuu-static-link.sln
      
    - name: Build dymatic solution
      run: msbuild /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} msvc/uuu.sln
