name: Build with VS Studio

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: ['Debug', 'Release']
        platform: ['x86', 'x64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Build static solution
      run: msbuild /p:Configuration=${{ matrix.configuration }} /p:PlatformToolset=v143 /p:Platform=${{ matrix.platform }} msvc/uuu-static-link.sln

    - name: Upload Build Artifacts
      if: matrix.configuration == 'Release' && matrix.platform == 'x64'
      uses: actions/upload-artifact@v3
      with:
        name: uuu.exe
        path: msvc/x64/Release/uuu.exe

    - name: Create or Update Release
      if: matrix.configuration == 'Release' && matrix.platform == 'x64'
      uses: ncipollo/release-action@v1
      with:
        name: Release UUU_1.5.${{ github.sha }}_TEST
        tag: UUU_1.5.${{ github.sha }}_TEST
        commit: ${{ github.hash }}
        allowUpdates: true
        draft: true
        prerelease: true
        artifacts: msvc/x64/Release/uuu.exe

    - name: Build dynamic solution
      run: msbuild /p:Configuration=${{ matrix.configuration }} /p:PlatformToolset=v143 /p:Platform=${{ matrix.platform }} msvc/uuu.sln
